package vc.xji.empty.mapper;

import org.apache.ibatis.annotations.Param;
import vc.xji.empty.entity.Permissions;
import vc.xji.empty.entity.UserPermission;

import java.util.List;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer permissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated
     */
    Permissions selectByPrimaryKey(Integer permissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Permissions record);

    List<Permissions> selectByUserId(Integer userId);

    int insertPermissions(@Param("list") List<UserPermission> list);
}